import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { renderMarkdown, getCollection, getEntry, slugify } from '../src/content.js';

describe('Drift SSG Content Collections & Markdown Engine', () => {
  let tmpContentDir: string;

  beforeEach(() => {
    tmpContentDir = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-ssg-content-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpContentDir, { recursive: true, force: true });
  });

  describe('slugify', () => {
    it('creates clean url slugs', () => {
      expect(slugify('Hello World!')).toBe('hello-world');
      expect(slugify('Register VM: Deep-Dive #1')).toBe('register-vm-deep-dive-1');
      expect(slugify('   multiple   spaces  ')).toBe('multiple-spaces');
    });
  });

  describe('renderMarkdown with gray-matter and marked', () => {
    it('extracts YAML frontmatter and renders markdown to semantic HTML with heading anchors', () => {
      const source = `---
title: "DriftJS Register VM"
author: "Hrutav"
tags: ["vm", "ssg", "compiler"]
draft: false
views: 1200
---

# Architecture Overview

DriftJS compiles Single File Components into **bytecode**.

## Bytecode Execution

Here is sample code:

\`\`\`ts
const vm = new DriftServerVM();
\`\`\`

* High performance
* Zero-JS by default
`;

      const result = renderMarkdown(source);

      // Verify frontmatter parsed by gray-matter
      expect(result.frontmatter['title']).toBe('DriftJS Register VM');
      expect(result.frontmatter['author']).toBe('Hrutav');
      expect(result.frontmatter['tags']).toEqual(['vm', 'ssg', 'compiler']);
      expect(result.frontmatter['draft']).toBe(false);
      expect(result.frontmatter['views']).toBe(1200);

      // Verify HTML generated by marked with heading anchors
      expect(result.html).toContain('<h1 id="architecture-overview">Architecture Overview</h1>');
      expect(result.html).toContain('<h2 id="bytecode-execution">Bytecode Execution</h2>');
      expect(result.html).toContain('<strong>bytecode</strong>');
      expect(result.html).toContain('<code class="language-ts">');
      expect(result.html).toContain('<li>High performance</li>');

      // Verify headings table of contents
      expect(result.headings).toEqual([
        { depth: 1, text: 'Architecture Overview', id: 'architecture-overview' },
        { depth: 2, text: 'Bytecode Execution', id: 'bytecode-execution' },
      ]);
    });
  });

  describe('getCollection and getEntry', () => {
    it('reads and filters content entries from directory', async () => {
      const blogDir = path.join(tmpContentDir, 'blog');
      fs.mkdirSync(blogDir);

      fs.writeFileSync(
        path.join(blogDir, 'first-post.md'),
        `---
title: "First Post"
published: true
---
# Hello First
`
      );

      fs.writeFileSync(
        path.join(blogDir, 'draft-post.md'),
        `---
title: "Draft Post"
published: false
---
# Hello Draft
`
      );

      const allPosts = await getCollection('blog', undefined, tmpContentDir);
      expect(allPosts.length).toBe(2);

      const publishedPosts = await getCollection(
        'blog',
        (entry) => entry.data.published === true,
        tmpContentDir
      );
      expect(publishedPosts.length).toBe(1);
      expect(publishedPosts[0]?.data.title).toBe('First Post');

      const entry = await getEntry('blog', 'first-post', tmpContentDir);
      expect(entry).toBeDefined();
      expect(entry?.data.title).toBe('First Post');
      expect(entry?.html).toContain('<h1 id="hello-first">Hello First</h1>');
    });
  });
});
