import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { renderMarkdown, getCollection, getEntry, slugify, scanMarkdownIslands, stripFrontmatter } from '../src/index.js';
import { unescapeHtml } from 'driftjs-shared';

describe('Drift SSG Content Collections & Markdown Engine', () => {
  let tmpContentDir: string;

  beforeEach(() => {
    tmpContentDir = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-ssg-content-test-'));
  });

  afterEach(() => {
    fs.rmSync(tmpContentDir, { recursive: true, force: true });
  });

  describe('slugify', () => {
    it('creates clean url slugs', () => {
      expect(slugify('Hello World!')).toBe('hello-world');
      expect(slugify('Register VM: Deep-Dive #1')).toBe('register-vm-deep-dive-1');
      expect(slugify('   multiple   spaces  ')).toBe('multiple-spaces');
    });
  });

  describe('renderMarkdown with gray-matter and marked', () => {
    it('extracts YAML frontmatter and renders markdown to semantic HTML with heading anchors', () => {
      const source = `---
title: "DriftJS Register VM"
author: "Hrutav"
tags: ["vm", "ssg", "compiler"]
draft: false
views: 1200
---

# Architecture Overview

DriftJS compiles Single File Components into **bytecode**.

## Bytecode Execution

Here is sample code:

\`\`\`ts
const vm = new DriftServerVM();
\`\`\`

* High performance
* Zero-JS by default
`;

      const result = renderMarkdown(source);

      // Verify frontmatter parsed by gray-matter
      expect(result.frontmatter['title']).toBe('DriftJS Register VM');
      expect(result.frontmatter['author']).toBe('Hrutav');
      expect(result.frontmatter['tags']).toEqual(['vm', 'ssg', 'compiler']);
      expect(result.frontmatter['draft']).toBe(false);
      expect(result.frontmatter['views']).toBe(1200);

      // Verify HTML generated by marked with heading anchors
      expect(result.html).toContain('<h1 id="architecture-overview">Architecture Overview</h1>');
      expect(result.html).toContain('<h2 id="bytecode-execution">Bytecode Execution</h2>');
      expect(result.html).toContain('<strong>bytecode</strong>');
      expect(result.html).toContain('<code class="language-ts">');
      expect(result.html).toContain('<li>High performance</li>');

      // Verify headings table of contents
      expect(result.headings).toEqual([
        { depth: 1, text: 'Architecture Overview', id: 'architecture-overview' },
        { depth: 2, text: 'Bytecode Execution', id: 'bytecode-execution' },
      ]);
    });
  });

  describe('getCollection and getEntry', () => {
    it('reads and filters content entries from directory', async () => {
      const blogDir = path.join(tmpContentDir, 'blog');
      fs.mkdirSync(blogDir);

      fs.writeFileSync(
        path.join(blogDir, 'first-post.md'),
        `---
title: "First Post"
published: true
---
# Hello First
`
      );

      fs.writeFileSync(
        path.join(blogDir, 'draft-post.md'),
        `---
title: "Draft Post"
published: false
---
# Hello Draft
`
      );

      const allPosts = await getCollection('blog', undefined, tmpContentDir);
      expect(allPosts.length).toBe(2);

      const publishedPosts = await getCollection(
        'blog',
        (entry) => entry.data.published === true,
        tmpContentDir
      );
      expect(publishedPosts.length).toBe(1);
      expect(publishedPosts[0]?.data.title).toBe('First Post');

      const entry = await getEntry('blog', 'first-post', tmpContentDir);
      expect(entry).toBeDefined();
      expect(entry?.data.title).toBe('First Post');
      expect(entry?.html).toContain('<h1 id="hello-first">Hello First</h1>');
    });
  });

  describe('drift exe live editor fences', () => {
    const liveSource = `# Demo

\`\`\`drift exe
<h1>Hello {name}</h1>
\`\`\`

\`\`\`ts
const vm = new DriftServerVM();
\`\`\`
`;

    it('promotes a "drift exe" fence into a DriftCodeEditor island container', () => {
      const result = renderMarkdown(liveSource);

      expect(result.html).toContain('data-drift-island="DriftCodeEditor"');
      expect(result.html).toContain('data-drift-trigger="eager"');
      expect(result.html).toContain('class="drift-md-editor"');
      expect(result.html).not.toContain('<pre><code class="language-drift exe">');

      const rawProps = /data-drift-props="([^"]*)"/.exec(result.html)![1]!;
      const props = JSON.parse(unescapeHtml(rawProps));
      expect(props.code).toBe('<h1>Hello {name}</h1>');
      expect(props.height).toBe('440px');
      expect(props.width).toBe('100%');
    });

    it('leaves every other fence as a static code block', () => {
      const result = renderMarkdown(liveSource);

      expect(result.html).toContain('<code class="language-ts">');
      expect(result.islands).toHaveLength(1);
    });

    it('reports the editor island descriptor for bundling', () => {
      const [island] = renderMarkdown(liveSource).islands;

      expect(island).toEqual({
        name: 'DriftCodeEditor',
        componentPath: 'driftjs-playground',
        exportName: 'DriftCodeEditor',
        trigger: 'eager',
        props: {
          code: '<h1>Hello {name}</h1>',
          height: '440px',
          width: '100%',
        },
      });
    });

    it('honours markdown island overrides from the project config', () => {
      const result = renderMarkdown(liveSource, {
        component: 'MyEditor',
        componentPath: './src/components/MyEditor.drift',
        exportName: undefined,
        trigger: 'visible',
        height: '300px',
        width: '80%',
        wrapperClass: 'md-editor',
        props: { theme: 'light' },
      });

      expect(result.html).toContain('data-drift-island="MyEditor"');
      expect(result.html).toContain('data-drift-trigger="visible"');
      expect(result.html).toContain('class="md-editor"');

      const [island] = result.islands;
      expect(island?.componentPath).toBe('./src/components/MyEditor.drift');
      expect(island?.exportName).toBeUndefined();
      expect(island?.props).toMatchObject({ theme: 'light', height: '300px', width: '80%' });
    });

    it('only matches the exact "drift exe" fence header', () => {
      const result = renderMarkdown(
        '```drift\nplain\n```\n\n```drift-exe\nplain\n```\n\n```DRIFT EXE\nupper\n```\n'
      );

      expect(result.html).toContain('<code class="language-drift">');
      expect(result.html).toContain('<code class="language-drift-exe">');
      expect(result.islands).toHaveLength(1);
      expect(result.islands[0]?.props.code).toBe('upper');
    });

    it('scans fences for island discovery without rendering HTML', () => {
      const islands = scanMarkdownIslands(
        '# Title\n\n```drift exe\n<p>One</p>\n```\n\n```drift exe\n<p>Two</p>\n```\n'
      );

      expect(islands).toHaveLength(2);
      expect(islands[0]?.props.code).toBe('<p>One</p>');
      expect(islands[1]?.props.code).toBe('<p>Two</p>');
      expect(scanMarkdownIslands('```ts\nconst a = 1;\n```\n')).toHaveLength(0);
    });

    it('strips frontmatter before scanning', () => {
      const source = '---\ntitle: "Doc"\n---\n\n```drift exe\n<p>Body</p>\n```\n';
      expect(scanMarkdownIslands(stripFrontmatter(source))).toHaveLength(1);
    });
  });
});
